// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgqijingtitjmrtvgcnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncWlqaW5ndGl0am1ydHZnY25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDM4NTksImV4cCI6MjA1ODk3OTg1OX0.iA6ZeJXDNxA9eJPs6VYRc2ymxAISDIYa-6Yai5a58U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);